### ISSUE TITLE
変愚「[Fix] スポイラーページの自動生成に失敗する 」のマージ

### ISSUE THREAD

**Issue by deskull-m** [sikabane-works/bakabakaband#3000]

**Comment by deskull-m** [comment]
## 判定結果: 作業不要（既に反映済み）

変愚蛮怒 PR hengband/hengband#2857「[Fix] github.io の自動生成スポイラーページの更新に失敗する」の内容を調査した結果、bakabakaband 側に既に同等の修正が適用されていることを確認しました。

### 上流 PR 概要
- hengband/hengband#2857
- 変更: `publish-spoiler-page.yml` に `submodules: true` を追加（2 行）
- 原因: スポイラー生成バイナリのビルド時にサブモジュールディレクトリが存在しないためエラー

### bakabakaband 側の現状
`.github/workflows/publish-spoiler-page.yml` line 16 で既に `submodules: true` が設定済み：

```yaml
      - uses: actions/checkout@v3
        with:
          submodules: true
```

### 結論
PR #2857 の内容が既に反映されているため、本 ISSUE はクローズします。

---
*この判定は Claude Code による自動解析に基づきます。*

---
_Generated by [Claude Code](https://claude.ai/code)_
